### ISSUE TITLE
docker pull command in README does not work

### ISSUE THREAD

**Issue by joelnitta** [camwebb/taxon-tools#14]
The README currently says

```
docker pull camwebb/taxon-tools
```

This command does not specify the tag, so Docker tries the default tag `latest`. However, there is no tag `latest` on [Docker hub](https://hub.docker.com/r/camwebb/taxon-tools/tags), so it fails:

```
(base) Joels-iMac:gbif_ferns joelnitta$ docker pull camwebb/taxon-tools
Using default tag: latest
Error response from daemon: manifest for camwebb/taxon-tools:latest not found: manifest unknown: manifest unknown
```

The solution is either to push a tag `latest` to Docker hub, or to specify a tag that exists (e.g., `docker pull camwebb/taxon-tools:v1.3.0`).

**Comment by camwebb** [comment]
Thanks. Fixed.
