### ISSUE TITLE
Parsing of infraspecific rank signifier works for "var." but not "ssp."

### ISSUE THREAD

**Issue by joelnitta** [camwebb/taxon-tools#6]
Is there a list of accepted abbreviated infraspecific rank signifiers? Apparently my data include some that don't work.

`8420R|Lycopodium clavatum var. aristatum (Humb. & Bonpl. ex Willd.) Spring` correctly parses to
`8420R||Lycopodium||clavatum|var.|aristatum|(Humb. & Bonpl. ex Willd.) Spring`,

but

`8418R|Lycopodium clavatum ssp. clavatum L.` incorrectly parses to
`8418R||Lycopodium||clavatum||ssp|. clavatum L.`

Other abbreviated infraspecific rank signifiers that are not "var." or "subsp." also fail (e.g., "subf.").

**Comment by camwebb** [comment]
* `ssp.` now converted to `subsp.` 
 * `subf.` added to Regexp
 * List of infraspecific rank signifiers: subsp., var., f., forma, fo., subf., taxon., prol., nothovar., lus.
