### ISSUE TITLE
make check fails

### ISSUE THREAD

**Issue by joelnitta** [camwebb/taxon-tools#9]
As of 6c651d6bdce52c42598f002915eae68d97a21373, `make check` fails:

```
(base) root@9c80772cbb78:/apps/taxon-tools# make check
** matchnames PASS **
** parsenames FAIL **
```

If I checkout the last commit before fixing #8 (50280571bcafa8070e653d114c096f4c7295899a), `make check` works:

```
(base) root@9c80772cbb78:/apps/taxon-tools# git checkout 50280571bcafa8070e653d114c096f4c7295899a
...
(base) root@9c80772cbb78:/apps/taxon-tools# make check
** matchnames PASS **
** parsenames PASS **
```

**Comment by camwebb** [comment]
Oops - forgot to update `test/parsenames.ok` when I changed `test/names` to add the diacritics as per [issue 8](https://github.com/camwebb/taxon-tools/issues/8). Fixed now.
